//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniTwitter.Resources.languages.jp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_jp() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniTwitter.Resources.languages.jp.Resource.jp", typeof(Resource_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à このタイムラインは編集できません。.
        /// </summary>
        internal static string can_not_edit_timeline {
            get {
                return ResourceManager.GetString("can_not_edit_timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 削除してよろしいですか？.
        /// </summary>
        internal static string delete_msg {
            get {
                return ResourceManager.GetString("delete_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 140文字を超えています。.
        /// </summary>
        internal static string exceeds_140_characters {
            get {
                return ResourceManager.GetString("exceeds_140_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à テーマの読み込みに失敗しました。.
        /// </summary>
        internal static string fail_load_theme {
            get {
                return ResourceManager.GetString("fail_load_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à キーボードマッピングの読み込みに失敗しました。.
        /// </summary>
        internal static string failed_load_keyword_mappings {
            get {
                return ResourceManager.GetString("failed_load_keyword_mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ブロックに失敗しました。.
        /// </summary>
        internal static string failed_to_block {
            get {
                return ResourceManager.GetString("failed_to_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à タイムラインの取得に失敗しました.
        /// </summary>
        internal static string failed_to_get_timeline {
            get {
                return ResourceManager.GetString("failed_to_get_timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 移動に失敗しました.
        /// </summary>
        internal static string failed_to_move {
            get {
                return ResourceManager.GetString("failed_to_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フォロー解除に失敗しました。.
        /// </summary>
        internal static string failed_to_release_follow_up {
            get {
                return ResourceManager.GetString("failed_to_release_follow_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  に取得完了.
        /// </summary>
        internal static string get_complete {
            get {
                return ResourceManager.GetString("get_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à フレンドタイムラインを取得しています....
        /// </summary>
        internal static string get_furendotaimurain {
            get {
                return ResourceManager.GetString("get_furendotaimurain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à リストを取得しています....
        /// </summary>
        internal static string get_list {
            get {
                return ResourceManager.GetString("get_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 返信タイムラインを取得しています....
        /// </summary>
        internal static string get_response_timeline {
            get {
                return ResourceManager.GetString("get_response_timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 検索結果を取得しています....
        /// </summary>
        internal static string get_results {
            get {
                return ResourceManager.GetString("get_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ダイレクトメッセージを取得しています....
        /// </summary>
        internal static string get_the_direct {
            get {
                return ResourceManager.GetString("get_the_direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 全てのタイムラインを取得しています....
        /// </summary>
        internal static string get_timeline_for_all {
            get {
                return ResourceManager.GetString("get_timeline_for_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ユーザータイムラインを取得しています....
        /// </summary>
        internal static string get_yuzataimurain {
            get {
                return ResourceManager.GetString("get_yuzataimurain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 既に起動しています。.
        /// </summary>
        internal static string has_already_started {
            get {
                return ResourceManager.GetString("has_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ユーザー名、パスワードが入力されていません.
        /// </summary>
        internal static string invalid_credentials {
            get {
                return ResourceManager.GetString("invalid_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ログインしています....
        /// </summary>
        internal static string logged_in {
            get {
                return ResourceManager.GetString("logged_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ログインに失敗しました.
        /// </summary>
        internal static string login_failed {
            get {
                return ResourceManager.GetString("login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 利用可能な更新はありません.
        /// </summary>
        internal static string no_available_update {
            get {
                return ResourceManager.GetString("no_available_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OAuth での認証に失敗しました.
        /// </summary>
        internal static string OAuth_authentication_failed {
            get {
                return ResourceManager.GetString("OAuth_authentication_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 名前を入力してください.
        /// </summary>
        internal static string please_enter_name {
            get {
                return ResourceManager.GetString("please_enter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReTweet に失敗しました.
        /// </summary>
        internal static string retweet_failed {
            get {
                return ResourceManager.GetString("retweet_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReTweet に成功しました.
        /// </summary>
        internal static string retweet_successful {
            get {
                return ResourceManager.GetString("retweet_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ReTweet しています....
        /// </summary>
        internal static string retweet_to {
            get {
                return ResourceManager.GetString("retweet_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à サウンドファイル|*.wav.
        /// </summary>
        internal static string sound_files {
            get {
                return ResourceManager.GetString("sound_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL の短縮が完了しました。.
        /// </summary>
        internal static string success_shorten_url_msg {
            get {
                return ResourceManager.GetString("success_shorten_url_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitpic へのアップロードが完了しました.
        /// </summary>
        internal static string success_twitpic_upload_msg {
            get {
                return ResourceManager.GetString("success_twitpic_upload_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitpic へアップロードしています....
        /// </summary>
        internal static string twitpic_to_upload {
            get {
                return ResourceManager.GetString("twitpic_to_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 対応していないフォーマットです.
        /// </summary>
        internal static string unsupported_format {
            get {
                return ResourceManager.GetString("unsupported_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 更新に失敗しました.
        /// </summary>
        internal static string update_failed {
            get {
                return ResourceManager.GetString("update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 利用可能な更新が見つかりました、今すぐ更新しますか？.
        /// </summary>
        internal static string update_msg {
            get {
                return ResourceManager.GetString("update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ステータスを更新しました.
        /// </summary>
        internal static string updated_status {
            get {
                return ResourceManager.GetString("updated_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ステータスを更新しています....
        /// </summary>
        internal static string updating_status {
            get {
                return ResourceManager.GetString("updating_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à URL を短く変換しています....
        /// </summary>
        internal static string URL_converted_to_short {
            get {
                return ResourceManager.GetString("URL_converted_to_short", resourceCulture);
            }
        }
    }
}
